spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_oauth2
    username: root
    password: 123456789
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 1021338613424-mjfoqf03hi8dfmv87mfm86ghqtqe908g.apps.googleusercontent.com
            clientSecret: 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
#            scope:
#              - email
#              - profile
          github:
            clientId: a81c6cc2a26000e1f31b
            clientSecret: 07b5fad800394cb151154b975e25f7740d958e03
            scope:
              - read:user
  flyway:
    baseline-on-migrate: true
    enabled: true
    user: root
    password: 123456789
    baseline-description: "init"
    baseline-version: 0